<?php

define('MORTAR_VERSION', '0.3.0');

define('APP_DIR', CLASS_DIR.'app'.DIRECTORY_SEPARATOR);
	define('APP_ROUTES', APP_DIR.'routes.php');
	define('APP_VIEWS', APP_DIR.'views'.DIRECTORY_SEPARATOR);
		define('VIEWS_TEMPLATES', APP_VIEWS.'templates'.DIRECTORY_SEPARATOR);
		define('VIEWS_COMPILED', APP_VIEWS.'compiled'.DIRECTORY_SEPARATOR);
